### PR TITLE
Upgrade to Java 8

### PR DESCRIPTION
**Pull request by hseeberger**

### CODE REVIEW

**Comment by hseeberger** [comment]
Anyone?

**Comment by pilwon** [comment]
@hseeberger We cannot merge this PR as it replaces `dockerfile` with `hseeberger` in README. We'll look into bringing Java 8 to this image.

**Comment by hseeberger** [comment]
@pilwon, sorry, I should have used a branch with just the Java update, i.e. without the latest commit changing the README. Did that now: https://github.com/dockerfile/java/pull/8

**Comment by pilwon** [comment]
@hseeberger Thanks, please follow the related issue #3

**Pull request closed without merging**
